services:
  db:
    image: postgres:15
    container_name: rust_paediatric_nutrition_db
    restart: always
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: rust_nutrition
    ports:
      - "5432:5432"
    volumes:
      - rust_nutrition_db_data:/var/lib/postgresql/data
      - ./db_init.sql:/docker-entrypoint-initdb.d/db_init.sql

volumes:
  rust_nutrition_db_data: